update

diff --git a/vendor/github.com/swaggo/swag/Makefile b/vendor/github.com/swaggo/swag/Makefile
--- a/vendor/github.com/swaggo/swag/Makefile
+++ b/vendor/github.com/swaggo/swag/Makefile
@@ -8,7 +8,6 @@ GOTEST=$(GOCMD) test
 GOGET=$(GOCMD) get
 GOLIST=$(GOCMD) list
 BINARY_NAME=swag
-PACKAGES=$(shell $(GOLIST) -f {{.Dir}} ./... | grep -v /example)
 
 all: test build
 
@@ -22,13 +21,21 @@ clean:
 	$(GOCLEAN)
 	rm -f $(BINARY_NAME)
 
+DIRS=$(shell $(GOLIST) -f {{.Dir}} ./...)
 lint:
-	for PKG in $(PACKAGES); do golint -set_exit_status $$PKG || exit 1; done;
+	@for d in $(DIRS) ; do \
+		if [ "`$(GOIMPORT) -l $$d/*.go | tee /dev/stderr`" ]; then \
+			echo "^ - Repo contains improperly formatted go files" && echo && exit 1; \
+		fi \
+	done
+	@if [ "`$(GOLINT) ./... | grep -vf .golint_exclude | tee /dev/stderr`" ]; then \
+		echo "^ - Lint errors!" && echo && exit 1; \
+	fi
 
 deps:
 	$(GOGET) -v ./...
 	$(GOGET) github.com/stretchr/testify/assert
-	$(GOGET) golang.org/x/lint/golint
+	$(GOGET) github.com/golang/lint/golint
 	$(GOGET) golang.org/x/tools/cmd/goimports
 
 view-covered:
